version: '3.8'
services:
  elasticsearch:
    container_name: ${APP_NAME}-elasticsearch
    image: bitnami/elasticsearch:8.5.0
    ports:
      - "${ES_PORT}:9200"
    environment:
      - xpack.security.enabled=false
      - network.host=127.0.0.1
      - http.host=0.0.0.0
    healthcheck:
      test: curl -u elastic:elastic -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 1s
      retries: 100