version: '3.8'
services:
  postgres:
    image: postgres:bullseye
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:9.17-alpine
    volumes:
      - ./sql:/flyway/sql
      - .env:/flyway/conf/.env
    command: "-url=jdbc:postgresql://postgres:5432/${DB_NAME} -user=${DB_USER} -password=${DB_PASSWORD} migrate"
    depends_on:
      - postgres

  app:
    build:
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - flyway

volumes:
  postgres-data:
